[package]
authors = ["Flier Lu <flier.lu@gmail.com>"]
build = "build.rs"
description = "A suite of non-cryptographic hash functions for Rust."
edition = "2018"
keywords = ["hash", "hashing"]
license = "Apache-2.0"
name = "fasthash-sys-fork"
version = "0.4.2"

[features]
default = ["native", "all"]

gen = ["bindgen"]

aes = []
avx = []
avx2 = ["avx"]
native = []
sse41 = []
sse42 = ["sse41"]

all = ["city", "farm", "highway", "lookup3", "meow", "metro", "mum", "murmur", "spooky", "t1ha", "wy", "xx"]
city = []
farm = []
highway = []
lookup3 = []
meow = []
metro = []
mum = []
murmur = []
spooky = []
t1ha = []
wy = []
xx = []

[dependencies]
cfg-if = "1.0"

[build-dependencies]
bindgen = {version = "0.59", optional = true}
cc = "1.0"
lazy_static = "1.4"
raw-cpuid = "10"
